/**
 * Каталог сущностей WORK (перенос work.prime-ltd.su).
 * listCols — как в live setting_fields (value=1) / personal.blade.
 */

/** @typedef {{
 *   key: string,
 *   label: string,
 *   type?: 'text'|'textarea'|'number'|'select'|'user'|'arrow-link'|'copy'|'specialists'|'days'|'favicon'|'staff-multi'|'staff-head'|'money'|'money-or-text'|'checkbox'|'select-status',
 *   group?: 'main'|'advanced',
 *   col?: '4'|'6'|'12',
 * }} WorkField */

/** Поля формы для назначения специалистов (sorts / work_assignees). */
const WORK_ASSIGNEE_FORM_FIELDS = [
    { key: 'assignee_legacy_ids', label: 'Специалисты', type: 'staff-multi', group: 'main', col: '12' },
    { key: 'id_glavn_user', label: 'Назначить главным', type: 'staff-head', group: 'main', col: '6' },
];

/** @type {Record<string, {
 *   slug: string,
 *   pageKey: string,
 *   table: string,
 *   title: string,
 *   subtitle: string,
 *   assigneeType?: number,
 *   showFavicon?: boolean,
 *   summaryKind?: 'seo'|'context'|'staff'|null,
 *   listCols: WorkField[],
 *   formFields: WorkField[],
 *   isStaff?: boolean
 * }>} */
const WORK_ENTITIES = {
    'seo-projects': {
        slug: 'seo-projects',
        pageKey: 'work-seo-projects',
        table: 'work_seo_projects',
        title: 'Проекты SEO',
        subtitle: 'Как на work.prime-ltd.su → Проекты SEO',
        assigneeType: 4,
        showFavicon: true,
        summaryKind: 'seo',
        listCols: [
            { key: 'favicon', label: '', type: 'favicon' },
            { key: 'name_project', label: 'Имя проекта', type: 'copy' },
            { key: 'password_match', label: 'Пароль SEO', type: 'match-status' },
            { key: 'dev_password_match', label: 'Пароль DEV', type: 'match-status' },
            { key: 'budget', label: 'Бюджет', type: 'money' },
            { key: 'osvoeno', label: 'Освоено', type: 'money' },
            { key: 'osvoeno_titlo', label: 'Освоено Титла', type: 'money' },
            { key: 'osvoeno_procent', label: 'Освоено %' },
            { key: 'specialists', label: 'Специалист', type: 'specialists' },
            { key: 'procent_seo', label: '% от проекта' },
            { key: 'summa_zp', label: 'Сумма на з.п.', type: 'money' },
            { key: 'startpoint', label: 'SP', type: 'arrow-link' },
            { key: 'start', label: 'Старт' },
            { key: 'end', label: 'Конец' },
            { key: 'days_left', label: 'Остаток дней', type: 'days' },
            { key: 'aim', label: 'Цель' },
            { key: 'region', label: 'Регион', type: 'copy' },
        ],
        formFields: [
            { key: 'name_project', label: 'Название проекта', group: 'main', col: '6' },
            { key: 'status', label: 'Статус', type: 'select-status', group: 'main', col: '3' },
            { key: 'our_project', label: 'Наш проект', type: 'checkbox', group: 'main', col: '3' },
            { key: 'promotion_type', label: 'Тип продвижения', group: 'main', col: '4' },
            { key: 'budget', label: 'Бюджет', group: 'main', col: '4' },
            { key: 'osvoeno', label: 'Освоено', group: 'main', col: '4' },
            { key: 'osvoeno_titlo', label: 'Освоено Титла', group: 'main', col: '4' },
            { key: 'osvoeno_procent', label: 'Освоено %', group: 'main', col: '4' },
            ...WORK_ASSIGNEE_FORM_FIELDS,
            { key: 'procent_seo', label: '% от проекта', group: 'main', col: '4' },
            { key: 'enable_procent_seo', label: 'Вкл %', type: 'checkbox', group: 'main', col: '4' },
            {
                key: 'summa_zp',
                label: 'Сумма на з.п.',
                group: 'main',
                col: '4',
                hint: 'Пересчитывается кнопкой «Пересчитать з.п.» по формуле выплат (можно править вручную).',
            },
            { key: 'startpoint', label: 'SP (URL)', group: 'main', col: '6' },
            { key: 'start', label: 'Старт', type: 'date', group: 'main', col: '4' },
            { key: 'end', label: 'Конец', type: 'date', group: 'main', col: '4' },
            { key: 'aim', label: 'Цель', group: 'main', col: '4' },
            { key: 'region', label: 'Регион', group: 'main', col: '4' },
            { key: 'dogovor_number', label: 'Договор', group: 'main', col: '4' },
            { key: 'contact_person', label: 'Контакт', group: 'main', col: '4' },
            { key: 'phone_person', label: 'Телефон', type: 'phone', group: 'main', col: '4' },
            { key: 'e_mail', label: 'E-mail', group: 'main', col: '4' },
            {
                key: 'procent_bonus',
                label: '% освоения для бонуса',
                type: 'number',
                group: 'advanced',
                col: '4',
                hint: '0 = брать из глобальных настроек выплат',
            },
            {
                key: 'count_day_fine',
                label: 'Дней до штрафа',
                type: 'number',
                group: 'advanced',
                col: '4',
                hint: 'После даты «Конец» + N дней. 0 = глобальные настройки',
            },
            {
                key: 'procent_fine',
                label: '% освоения для штрафа',
                type: 'number',
                group: 'advanced',
                col: '4',
                hint: 'Штраф если освоено % ниже порога. 0 = глобальные',
            },
            {
                key: 'procent_for_fine',
                label: '% базы для штрафа',
                type: 'number',
                group: 'advanced',
                col: '4',
                hint: '(бюджет − освоено) × % / 100. 0 вместе с другими порогами → глобальные',
            },
            {
                key: 'bonus_add',
                label: '% бонуса на этапе вывода',
                type: 'number',
                group: 'advanced',
                col: '4',
            },
            {
                key: 'bonus_enable',
                label: 'Свой % бонуса вывода',
                type: 'checkbox',
                group: 'advanced',
                col: '4',
                hint: 'Вкл. — брать bonus_add проекта; выкл. — глобальный bonus_add',
            },
        ],
    },
    'seo-passwords': {
        slug: 'seo-passwords',
        pageKey: 'work-seo-passwords',
        table: 'work_seo_passwords',
        title: 'Пароли SEO',
        subtitle: 'Как на work.prime-ltd.su → Пароли SEO',
        assigneeType: 1,
        showFavicon: true,
        listCols: [
            { key: 'favicon', label: '', type: 'favicon' },
            { key: 'name_project', label: 'Имя проекта', type: 'copy' },
            { key: 'project_match', label: 'Проект', type: 'match-status' },
            { key: 'specialists', label: 'Специалист', type: 'specialists' },
            { key: 'admin_url', label: 'Админка', type: 'copy' },
            { key: 'admin_login', label: 'Логин', type: 'copy' },
            { key: 'admin_pass', label: 'Пароль', type: 'copy' },
            { key: 'ssa', label: 'SSH' },
            { key: 'ftp', label: 'FTP', type: 'copy' },
            { key: 'login', label: 'Логин', type: 'copy' },
            { key: 'password', label: 'Пароль', type: 'copy' },
        ],
        formFields: [
            { key: 'name_project', label: 'Название' },
            { key: 'status', label: 'Статус', type: 'select-status' },
            ...WORK_ASSIGNEE_FORM_FIELDS,
            { key: 'ssa', label: 'SSH', type: 'textarea' },
            { key: 'ftp', label: 'FTP', type: 'textarea' },
            { key: 'admin_url', label: 'Admin URL' },
            { key: 'admin_login', label: 'Admin login' },
            { key: 'admin_pass', label: 'Admin pass' },
            { key: 'login', label: 'Логин' },
            { key: 'password', label: 'Пароль' },
            { key: 'positions', label: 'Позиция', type: 'number' },
            { key: 'value_serialize', label: 'Доп. поля', type: 'textarea' },
        ],
    },
    'dev-passwords': {
        slug: 'dev-passwords',
        pageKey: 'work-dev-passwords',
        table: 'work_dev_passwords',
        title: 'Пароли DEV',
        subtitle: 'Как на work.prime-ltd.su → Пароли Develop',
        assigneeType: 3,
        showFavicon: true,
        listCols: [
            { key: 'favicon', label: '', type: 'favicon' },
            { key: 'name_project', label: 'Имя проекта', type: 'copy' },
            { key: 'project_match', label: 'Проект SEO', type: 'match-status' },
            { key: 'specialists', label: 'Специалист', type: 'specialists' },
            { key: 'admin_url', label: 'Админка', type: 'copy' },
            { key: 'admin_login', label: 'Логин', type: 'copy' },
            { key: 'admin_pass', label: 'Пароль', type: 'copy' },
            { key: 'ssa', label: 'SSH' },
            { key: 'ftp', label: 'FTP', type: 'copy' },
            { key: 'login', label: 'Логин', type: 'copy' },
            { key: 'password', label: 'Пароль', type: 'copy' },
        ],
        formFields: [
            { key: 'name_project', label: 'Название' },
            { key: 'status', label: 'Статус', type: 'select-status' },
            ...WORK_ASSIGNEE_FORM_FIELDS,
            { key: 'admin_url', label: 'Admin URL' },
            { key: 'admin_login', label: 'Admin login' },
            { key: 'admin_pass', label: 'Admin pass' },
            { key: 'ssa', label: 'SSH', type: 'textarea' },
            { key: 'ftp', label: 'FTP', type: 'textarea' },
            { key: 'login', label: 'Логин' },
            { key: 'password', label: 'Пароль' },
            { key: 'positions', label: 'Позиция', type: 'number' },
            { key: 'value_serialize', label: 'Доп. поля', type: 'textarea' },
        ],
    },
    'context-projects': {
        slug: 'context-projects',
        pageKey: 'work-context-projects',
        table: 'work_context_projects',
        title: 'Проекты контекст',
        subtitle: 'Как на work.prime-ltd.su → Проекты Контекст',
        assigneeType: 5,
        showFavicon: true,
        summaryKind: 'context',
        listCols: [
            { key: 'favicon', label: '', type: 'favicon' },
            { key: 'name_project', label: 'Имя проекта', type: 'copy' },
            { key: 'password_match', label: 'Пароль', type: 'match-status' },
            { key: 'ya_direct', label: 'Я.Директ', type: 'money-or-text' },
            { key: 'specialists', label: 'Специалист', type: 'specialists' },
            { key: 'procent_seo', label: '%' },
            { key: 'sum_zp', label: 'Сумма на з.п.', type: 'money' },
        ],
        formFields: [
            { key: 'name_project', label: 'Название', group: 'main', col: '6' },
            { key: 'status', label: 'Статус', type: 'select-status', group: 'main', col: '3' },
            { key: 'our_project', label: 'Наш проект', type: 'checkbox', group: 'main', col: '3' },
            { key: 'ya_direct', label: 'Я.Директ (бюджет)', group: 'main', col: '4' },
            { key: 'procent_seo', label: '% от проекта', group: 'main', col: '4' },
            ...WORK_ASSIGNEE_FORM_FIELDS,
            { key: 'dogovor_number', label: 'Договор', group: 'main', col: '4' },
            { key: 'contact_person', label: 'Контакт', group: 'main', col: '4' },
            { key: 'phone_person', label: 'Телефон', group: 'main', col: '4' },
            { key: 'e_mail', label: 'E-mail', group: 'main', col: '4' },
        ],
    },
    'context-passwords': {
        slug: 'context-passwords',
        pageKey: 'work-context-passwords',
        table: 'work_context_passwords',
        title: 'Пароли контекст',
        subtitle: 'Как на work.prime-ltd.su → Пароли Контекст',
        assigneeType: 2,
        showFavicon: true,
        listCols: [
            { key: 'favicon', label: '', type: 'favicon' },
            { key: 'name_project', label: 'Имя проекта', type: 'copy' },
            { key: 'project_match', label: 'Проект', type: 'match-status' },
            { key: 'specialists', label: 'Специалист', type: 'specialists' },
            { key: 'loginYandex', label: 'Логин Яндекс', type: 'copy' },
            { key: 'passYandex', label: 'Пароль Яндекс', type: 'copy' },
            { key: 'loginGoogle', label: 'Логин Гугл', type: 'copy' },
            { key: 'passGoogle', label: 'Пароль Гугл', type: 'copy' },
        ],
        formFields: [
            { key: 'name_project', label: 'Название', col: '6' },
            { key: 'status', label: 'Статус', type: 'select-status', col: '3' },
            ...WORK_ASSIGNEE_FORM_FIELDS,
            { key: 'loginYandex', label: 'Логин Яндекс', type: 'textarea', col: '6' },
            { key: 'passYandex', label: 'Пароль Яндекс', type: 'textarea', col: '6' },
            { key: 'loginGoogle', label: 'Логин Google', col: '6' },
            { key: 'passGoogle', label: 'Пароль Google', col: '6' },
        ],
    },
    services: {
        slug: 'services',
        pageKey: 'work-services',
        table: 'work_services',
        title: 'Сервисы & Пароли',
        subtitle: 'Как на work.prime-ltd.su → Сервисы и пароли',
        assigneeType: 6,
        showFavicon: true,
        listCols: [
            { key: 'favicon', label: '', type: 'favicon' },
            { key: 'name_project', label: 'Имя проекта', type: 'copy' },
            { key: 'specialists', label: 'Специалист', type: 'specialists' },
            { key: 'login', label: 'Логин', type: 'copy' },
            { key: 'password', label: 'Пароль', type: 'copy' },
        ],
        formFields: [
            { key: 'name_project', label: 'Название' },
            { key: 'status', label: 'Статус', type: 'select-status' },
            ...WORK_ASSIGNEE_FORM_FIELDS,
            { key: 'login', label: 'Логин' },
            { key: 'password', label: 'Пароль' },
            { key: 'dop_infa', label: 'Доп. информация', type: 'textarea' },
            { key: 'positions', label: 'Позиция', type: 'number' },
        ],
    },
    'seo-staff': {
        slug: 'seo-staff',
        pageKey: 'work-seo-staff',
        table: 'work_seo_staff',
        title: 'Сотрудники SEO',
        subtitle: 'Как на work.prime-ltd.su → Персонал',
        isStaff: true,
        summaryKind: 'staff',
        // Колонки списка как personal.blade: бонусы/итог считаются (HomeController@personal).
        listCols: [
            { key: 'datagon_user_name', label: 'Сотрудник' },
            { key: 'specialism', label: 'Специализация' },
            { key: 'level', label: 'Уровень' },
            { key: 'seo_projects_count', label: 'Проекты SEO' },
            { key: 'context_projects_count', label: 'Проекты Контекст' },
            { key: 'procent_seo_itog', label: 'Бонус от проекта SEO', type: 'money' },
            { key: 'sum_many_first', label: 'Оклад', type: 'money-or-text' },
            { key: 'context_bonus_itog', label: 'Бонус от проекта контекста', type: 'money' },
            { key: 'procent_context_itog', label: 'Сумма на зп', type: 'money' },
            { key: 'itog', label: 'Итог', type: 'money' },
        ],
        formFields: [
            { key: 'datagon_user_id', label: 'Сотрудник Datagon', type: 'user' },
            { key: 'email', label: 'E-mail (legacy)' },
            { key: 'specialism', label: 'Специализация' },
            { key: 'level', label: 'Уровень' },
            { key: 'personal_specialism', label: 'Специалист' },
            { key: 'seo_procent', label: '% SEO (ставка в карточке)' },
            { key: 'sum_many_first', label: 'Оклад' },
            { key: 'contecst_procent', label: '% контекст (ставка в карточке)' },
            { key: 'status', label: 'Статус', type: 'select-status' },
            { key: 'positions', label: 'Позиция', type: 'number' },
            { key: 'name', label: 'ФИО legacy (архив)', type: 'text' },
        ],
    },
};

function getWorkEntity(slug) {
    return WORK_ENTITIES[slug] || null;
}

function listWorkEntities() {
    return Object.values(WORK_ENTITIES);
}

module.exports = {
    WORK_ENTITIES,
    WORK_ASSIGNEE_FORM_FIELDS,
    getWorkEntity,
    listWorkEntities,
};
